language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.6
  - DJANGO=1.5.2
install:
  - pip install coverage flake8
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - PYTHONPATH=. django-admin.py test --settings="django_crontab.tests.test_settings" django_crontab