language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
    - python: "3.3"
      env: DJANGO=1.4
    - python: "3.4"
      env: DJANGO=1.4
cache: pip
install:
  - pip install flake8 coveralls
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.settings nosetests --with-coverage --cover-package=django_crontab
after_success:
  - coveralls
