language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.15
  - DJANGO=1.5.10
  - DJANGO=1.6.7
install:
  - pip install coverage flake8
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.settings nosetests
  - coverage report
