language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - pip install coverage flake8
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.test_settings nosetests
  - coverage report
