language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - REQUIREMENTS="django>=1.7,<1.8"
  - REQUIREMENTS="django>=1.8,<1.9"
  - REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
matrix:
  exclude:
    - python: "3.5"
      env: REQUIREMENTS="django>=1.7,<1.8"
    - python: "3.5"
      env: REQUIREMENTS="django>=1.8,<1.9"
    allow_failures:
      - env: REQUIREMENTS="https://github.com/django/django/archive/master.tar.gz"
cache: pip
install:
  - pip install flake8 coveralls $REQUIREMENTS
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - DJANGO_SETTINGS_MODULE=tests.settings nosetests --with-coverage --cover-package=django_crontab
after_success:
  - coveralls
