language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - pip install coverage flake8
  - pip install Django==$DJANGO
  - pip install -e .
script:
  - flake8 django_crontab --ignore=E501
  - PYTHONPATH=. coverage run --branch --source=django_crontab `which django-admin.py` test --settings="django_crontab.tests.test_settings" django_crontab
  - coverage report